/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/status": {
    get: operations["getStatus"];
  };
  "/character": {
    get: operations["getCharacters"];
    post: operations["addCharacter"];
  };
  "/character/{id}": {
    put: operations["updateCharacter"];
    delete: operations["deleteCharacter"];
  };
}

export interface components {
  schemas: {
    Character: {
      /** Format: int64 */
      id?: number;
      name?: string;
      description?: string;
      image_url?: string;
    };
    CharacterAdd: {
      name: string;
      description: string;
      image_url: string;
    };
    ApiErrorResponse: {
      code: string;
      message: string;
    };
    /** @description Server encountered an unexpected condition */
    InternalServerError: components["schemas"]["ApiErrorResponse"];
    /** @description Can not process request because of client error */
    BadRequest: components["schemas"]["ApiErrorResponse"];
    /** @description The specified resource was not found */
    ResourceNotFound: components["schemas"]["ApiErrorResponse"];
  };
}

export interface operations {
  getStatus: {
    responses: {
      200: {
        content: {
          "text/plain": string;
        };
      };
    };
  };
  getCharacters: {
    responses: {
      /** successful operation */
      200: {
        content: {
          "application/json": {
            data: components["schemas"]["Character"][];
          };
        };
      };
      500: components["schemas"]["InternalServerError"];
    };
  };
  addCharacter: {
    responses: {
      /** successful operation */
      201: {
        content: {
          "application/json": {
            data: components["schemas"]["Character"];
          };
        };
      };
      /** Invalid name */
      400: components["schemas"]["BadRequest"];
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CharacterAdd"];
      };
    };
  };
  updateCharacter: {
    parameters: {
      path: {
        /** ID of character to update */
        id: number;
      };
    };
    responses: {
      /** successful operation */
      200: unknown;
      404: components["schemas"]["ResourceNotFound"];
    };
    /** Update character object */
    requestBody: {
      content: {
        "application/json": components["schemas"]["CharacterAdd"];
      };
    };
  };
  deleteCharacter: {
    parameters: {
      path: {
        /** ID of character to update */
        id: number;
      };
    };
    responses: {
      /** successful operation */
      200: unknown;
      404: components["schemas"]["ResourceNotFound"];
    };
  };
}

export interface external {}
