version: '3'

services:
  api:
    build:
      context: .
      args:
        NODE_ENV: development
    command: npm run dev
    env_file:
      - ./config/.dev.env
    volumes:
      - ./:/app
      - /app/node_modules

  db:
    env_file:
      - ./config/.dev.env
