version: '3'

services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - '3000:3000'
    env_file:
      - ./config/.dev.env

  db:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=kakarot
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kakarot
      - PGDATA=/var/data/postgres
    volumes:
      - db-data:/var/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
    driver: local
